CREATE DATABASE IF NOT EXISTS CUSTOMER360_V2;
USE DATABASE CUSTOMER360_V2;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS PROCESSING;
CREATE SCHEMA IF NOT EXISTS IDENTITY;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS CONFIG;
CREATE SCHEMA IF NOT EXISTS EXPORT;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FF
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE;
